<script setup lang="ts">
import DocsTerminalBlock from '~/components/Docs/TerminalBlock.vue'
import DocsCodeBlock from '~/components/Docs/CodeBlock.vue'

const terminalCommands = {
  npm: 'npm run dev',
  pnpm: 'pnpm dev',
  yarn: 'yarn dev',
  bun: 'bun dev'
}

const sampleCode = `import type { Metadata } from 'next'
import { ClerkProvider, Show, SignInButton, SignUpButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        class={\`\${geistSans.variable} \${geistMono.variable} antialiased\`}
      >
        <ClerkProvider>
          {children}
        </ClerkProvider>
      </body>
    </html>
  )
}
`
</script>

<template>
  <div class="min-h-screen bg-black text-white p-12 flex justify-center">
    <div class="max-w-3xl w-full space-y-12">
      <div>
        <h2 class="text-2xl font-bold mb-6">Terminal Block</h2>
        <DocsTerminalBlock :commands="terminalCommands" />
      </div>

      <div>
        <h2 class="text-2xl font-bold mb-6">Expandable Code Block</h2>
        <DocsCodeBlock 
          :code="sampleCode" 
          lang="tsx" 
          filename="app/layout.tsx" 
          expandable
          maxHeight="250px"
        />
      </div>
      
      <div>
        <h2 class="text-2xl font-bold mb-6">Simple Code Block</h2>
        <DocsCodeBlock 
          code="console.log('Hello from docs!')" 
          lang="typescript" 
        />
      </div>
    </div>
  </div>
</template>
